### ISSUE TITLE
If validation fails, it doesn't abort accordingly

### ISSUE THREAD

**Issue by taschik** [BranchMetrics/fastlane-plugin-branch#43]
Hi,

I am integrating the branch.io fastlane plugin into our pipeline and provoked an error to see, if it fails the pipeline in case something is not correct. In the following example, I'd expected the fastlane plugin to throw an appropriate error that stops the pipeline. 

```
Validating Debug configuration

Project domains match :domains parameter: ✅
GET https://xxx.test-app.link/.well-known/apple-app-site-association: 200 OK (Content-type:application/json; charset=utf-8) ✅
Universal Link configuration failed validation for Debug configuration.
 [xxx.test-app.link] appID mismatch. Project Signing team: "XXXXXXXX", Bundle identifier: "com.xxx.dev"
 Apps from AASA:
  Signing team: "YYYYYYYYYY", Bundle identifier: "com.xxx.dev"
```

Is there a specific parameter necessary to make the script fail or what is the best practice to catch a misconfigured / broken branch setup within a fastlane pipeline? 

Thanks a lot!

**Comment by jdee** [comment]
Hi @taschik. The return value of the action indicates whether it succeeded or failed. I've sometimes thought it should raise an exception. This is good feedback. We could do an update that raises. For now, you can do this in your Fastfile:

```ruby
lane :validate do
  UI.user_error! "Project failed Universal Link validation." unless validate_universal_links(...)

  # do any further validation or other tasks
end
```

logging methods on `UI` that end in an exclamation point (!) raise exceptions and terminate execution of a lane.

Or you can handle the `false` return value any way you like.

**Comment by jdee** [comment]
Closing this issue. We can consider adding an option to raise on failure separately.

**Comment by taschik** [comment]
@jdee Thanks so much for the proposal. This works like a charm as a workaround until you guys add the raise. Appreciate your support!
